services:
  api:
    build: 
      context: ..
      target: production
    container_name: blog_api_prod
    restart: always
    env_file:
      - ../.env
    environment:
      NODE_ENV: production
      PORT: 3000
      TZ: Asia/Phnom_Penh

  nginx:
    image: nginx:1.27-alpine
    container_name: nginx_proxy_prod
    restart: always
    environment:
      TZ: Asia/Phnom_Penh
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../nginx/nginx.prod.conf:/etc/nginx/nginx.conf:ro
      - ../nginx/certbot/conf:/etc/letsencrypt:ro
      - ../nginx/certbot/www:/var/www/certbot:ro   
    depends_on:
      - api

  certbot:                                        # ADD THIS
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ../nginx/certbot/conf:/etc/letsencrypt    # no :ro — certbot needs to WRITE here
      - ../nginx/certbot/www:/var/www/certbot
