services:
  api:
    image: ghcr.io/blogpostangular/backend-api:latest
    container_name: blog_api_prod
    restart: always
    env_file:
      - ../.env
    environment:
      NODE_ENV: production
      PORT: 3000
      TZ: Asia/Phnom_Penh
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  nginx:
    image: nginx:1.27-alpine
    container_name: nginx_proxy_prod
    restart: always
    environment:
      TZ: Asia/Phnom_Penh
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../nginx/nginx.prod.conf:/etc/nginx/nginx.conf:ro
      - ../nginx/certbot/conf:/etc/letsencrypt:ro
      - ../nginx/certbot/www:/var/www/certbot:ro
    depends_on:
      - api
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ../nginx/certbot/conf:/etc/letsencrypt
      - ../nginx/certbot/www:/var/www/certbot
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  app-network:
    driver: bridge